// lab4-angular-instrumentos/src/app/components/Detalle/detalle.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { Instrumento } from "src/app/model/instrumento";
import { Home } from "../Home/home.component";

@Component({
    selector: 'app-detalle',
    templateUrl: './detalle.component.html',
    providers:[ Home ] //indicamos que Home es padre de Detalle
})
export class Detalle implements OnInit { 

    jsonData:Instrumento = {
        cantidadVendida:null, costoEnvio:null, descripcion:null, id:null, imagen:null, instrumento:null,
        marca:null, modelo:null, precio:null
    };

    constructor(
        private home:Home,
        private route:ActivatedRoute
    ) {}

    ngOnInit(): void { 
        this.getDetalle();
    }

    //filtra los datos traidos desde Home con el código de la ruta de la página actual
    getDetalle(){
        let arreglosJson = this.home.getData();
        for(let i=0; i<arreglosJson.length; i++){         
            if(arreglosJson[i].id.toString() === this.route.snapshot.params.codigo){ 
                this.jsonData = arreglosJson[i];
                console.log(this.jsonData)
            }
        }
    }

}
<div style="margin:10px">
    <div class="card" style="width: 600px;">                   
        <div class="card-body">
            <img class="card-img-top" style="width: 150px; height: 150px; margin:10px;" [src]="jsonData.imagen">
            <h5 class="card-title"> {{ jsonData.instrumento }} </h5>
            <div *ngIf="jsonData.costoEnvio==='G'" style="color: #3cb21b"> Envio a Todo el País </div>
            <div *ngIf="jsonData.costoEnvio!=='G'" style="color: #ec7a2c"> Costo Envio Interior De Argentina ${{ jsonData.precio }} </div>
            <div> Vendidos: {{ jsonData.cantidadVendida }} </div>
            Descripción:
            <div> {{ jsonData.descripcion }} </div>
            <hr/>
            <a class="btn btn-dark" href="/">Volver</a>            
        </div>
    </div>
</div>

// lab4-vue-instrumentos/src/components/Detalle.vue
<template> 
  <div> 
    <div style="width: auto;">
        <div style="margin:10px">
            <b-card style="width: 500px;">
                <img v-bind:src="dataRecibida.imagen" style="max-width: 100px; margin-bottom: 10px;"> 
                <h5 style="font-weight: bold;"> {{ dataRecibida.instrumento }} </h5> 
                <div> Marca: {{ dataRecibida.marca }} </div>
                <div> Modelo: {{ dataRecibida.modelo }} </div>
                <div v-if="dataRecibida.costoEnvio==='G'" style="color: #3cb21b "> Envio a Todo el divaís </div>
                <div v-else style="color: #ec7a2c "> Costo Envio Interior De Argentina ${{ dataRecibida.divrecio }} </div>

                <div> Vendidos: {{ dataRecibida.cantidadVendida }} </div>
                Descripción:
                <div> {{ dataRecibida.descripcion }} </div>
                <hr/>
                <router-link class="btn btn-dark" v-bind:to="`/`"> Volver </router-link>
            </b-card>
        </div>
    </div>

  </div> 
</template> 
 
<script> //-----------------------------------------SCRIPT--------------------------------------------
export default{ 
    name:'Detalle',
    
    data()  {
        console.log(this.$route.query);
        return {
            dataRecibida:this.$route.query.detalleItem
        }
    }, 
 }

</script>
