// lab4-angular-instrumentos/src/app/components/Home/home.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import { Service } from "src/app/service/service.service";

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls:['./home.component.css']
})
export class Home implements OnInit {

    datosArray:any;
    datosFiltrados:any;

    //variable para pipe
    filterPost = '';

    constructor(
        private router:Router,
        private service:Service
    ) {}

    ngOnInit(): void {       
        this.getData();
    }

    //trae los datos desde el Service
    getData(){
        this.datosArray = this.service.getData();
        this.datosFiltrados = this.datosArray;

        return this.datosFiltrados;
    }

    //redirecciona a la página de Detalle
    detalle(id){
        this.router.navigate(['detalle/'+id]);        
    }

    buscadorInput(dataInput){ //filtro que funciona
        let resultadoFiltrado = [];    
        let value = dataInput.value.toLowerCase();
        console.log(value);
        resultadoFiltrado = this.getData().filter( (array) => {
            return array.instrumento.toLowerCase().search(value) !== -1; // return a boolean
        });
        console.log(resultadoFiltrado);
        this.datosFiltrados = resultadoFiltrado;
    }
    

}
<input class="form-control" type="text" placeholder="Buscar planeta..." style="width: 255px;"
name="filterPost" [(ngModel)]="filterPost">

<div class="d-flex flex-wrap">
    <div style="margin:10px" *ngFor="let item of datosArray | filter:filterPost">
        <div class="card" style="width: 300px;">
            <img class="card-img-top" style="width: 100px; height: 100px; margin: 10px;" [src]="item.imagen">            
            <div class="card-body">
                <h5 class="card-title"> {{ item.instrumento }} </h5>
                <div *ngIf="item.costoEnvio==='G'" style="color: #3cb21b"> Envio a Todo el País </div>
                <div *ngIf="item.costoEnvio!=='G'" style="color: #ec7a2c"> Costo Envio Interior De Argentina ${{ item.precio }} </div>
                <div> Vendidos: {{ item.cantidadVendida }} </div>
                <hr/>
                <a class="btn btn-dark" (click)="detalle(item.id)"> Detalle </a>
            </div>
          </div>
    </div>
</div>

// lab4-vue-instrumentos/src/components/Home.vue
<template>
    <div>
       <h3 style="margin:10px"> Catálogo de Instrumentos </h3>
    
        <div class="d-flex flex-wrap" style="width: auto;">
            <div v-for="(item, i) in datosArray" :key="i" style="margin:10px">
                <b-card style="width: 300px;">
                    <img v-bind:src="item.imagen" style="max-width: 100px; margin-bottom: 10px;"> 
                    <h5 style="font-weight: bold;"> {{ item.instrumento }} </h5>

                    <div v-if="item.costoEnvio==='G'" style="color: #3cb21b "> Envio a Todo el País </div>
                    <div v-else style="color: #ec7a2c "> Costo Envio Interior De Argentina ${{ item.precio }} </div>
                    <div> Vendidos: {{ item.cantidadVendida }} </div>
                    <hr/>
                    <router-link class="btn btn-dark" :to="{ path: '/detalle/'+item.id, query: { detalleItem:item } }" > Detalles </router-link>
                </b-card>
            </div>
        </div>
        
    </div>
</template>

<script> //-----------------------------------------SCRIPT--------------------------------------------
export default{
    name:'Home',
    props: {
        datosArray:Array
    },

}
</script>
